package com.bengel.shared.core

object TurkishFraudConstants {

    val BTK_SPAM_CODES: Set<String> = setOf(
        "B214", "B217", "B250", "B312", "B445",
    )

    // ── BETTING / GAMBLING ────────────────────────────────────────────────────
    val BETTING_KEYWORDS: Set<String> = setOf(
        // Core Turkish
        "bahis", "bahiis", "bahiss", "bah1s", "bah!s", "b-a-h-i-s",
        "casino", "casin0", "cas1no", "kasino", "kazino", "casiino",
        "kumar", "slot", "rulet", "poker", "blackjack", "jackpot", "ikramiye",

        // English core
        "bet", "bets", "betting", "bettor",
        "free bet", "freebet", "free-bet",
        "freespin", "free spin", "free-spin", "fríspin",
        "bet365", "bet-365", "1xbet", "1x bet", "1xbahis", "22bet",
        "win", "winwin", "winning", "odds", "odd",
        "stake", "stakes", "wager", "wagering",
        "punt", "punter", "accumulator", "acca",
        "parlay", "combo bet", "handicap", "asian handicap",
        "live bet", "livebet", "in-play",
        "cashout", "cash out", "cash-out",
        "arbitrage", "arb bet", "sure bet", "surebet",
        "matched bet", "matchedbet",

        // Deneme bonusu variations
        "deneme", "deneme bonusu", "deneme bonus", "d3neme", "d-e-n-e-m-e",
        "ücretsiz deneme", "ucretsiz deneme", "bedava deneme",
        "deneme firsati", "ilk deneme", "trial bonus",

        // Bonus variations
        "bonus", "bonusu", "bonuss", "b0nus",
        "hosgeldin bonusu", "hos geldin bonusu",
        "ilk yatirim bonusu", "yatirim bonusu",
        "cevrimsiz bonus", "çevrimsiz bonus",
        "cevrim sarti yok", "çevrim şartı yok",
        "yatirimsiz bonus", "yatırımsız bonus",
        "kayipsiz bonus", "kayıpsız bonus",
        "iade bonusu", "cashback bonus", "geri odeme bonusu",
        "kayip bonusu", "kayıp bonusu",
        "vip bonus", "vip uyelik", "vip üyelik",
        "ozel bonus", "özel bonus", "ekstra bonus",
        "gunluk bonus", "günlük bonus", "haftalik bonus", "haftalık bonus",
        "dogum gunu bonusu", "doğum günü bonusu",
        "arkadasini getir", "arkadaş getir bonusu",
        "combo bonus", "coklu bonus", "çoklu bonus",
        "aninda bonus", "anında bonus", "otomatik bonus",
        "bonus kodu", "promosyon kodu", "promo kod",
        "kupon kodu", "referans kodu",
        "%100 bonus", "çift bonus",
        "bedava donus", "bedava dönüş",

        // Para / çekim
        "yatirim", "yatırım", "yat1r",
        "para yatir", "para yatır",
        "cekim", "çekim", "para cek", "para çek",
        "hizli cekim", "hızlı çekim", "aninda odeme", "anında ödeme", "7/24 odeme",
        "papara", "p-a-p-a-r-a", "papar@", "p@p@r@",

        // Kripto ödeme
        "kripto", "kript0", "bitcoin", "b1tcoin", "btc",
        "usdt", "u-s-d-t", "tether",

        // Oyna / giriş
        "oyna", "oyn4", "0yna", "hemen oyna",
        "siteye gir", "siteye girin",
        "giris yap", "giriş yap",
        "giris linki", "giriş linki",
        "kayit ol", "kayıt ol", "kay1t ol",
        "uye ol", "üye ol", "uye olun", "üye olun",
        "hesap ac", "hesap aç",

        // Kazanç
        "para kazan", "para kazanin",
        "kazanc", "kazançlı", "kazancli",
        "gunluk kazanc", "günlük kazanç",
        "garantili kazanc", "garantili kazanç",

        // Bahis terimleri
        "bahse gir", "bahse girin",
        "oran", "oranlar", "yuksek oran", "yüksek oran",
        "mac tahmini", "maç tahmini", "tahmin",
        "kupon", "kuponu doldur",
        "kombine", "sistem bahis",
        "canli", "canlı",
        "ganyan", "at yarisi", "at yarışı",
        "toto", "milli piyango", "piyango",
        "sans oyunu", "şans oyunu",
        "tombala", "bingo",
        "iddaa", "canli bahis", "canlı bahis", "spor bahis",
        "canli casino", "canlı casino",
        "sinirli sure", "sınırlı süre", "sadece bugun", "sadece bugün",
        "son sans", "son şans",
        "ozel teklif", "özel teklif", "buyuk ikramiye", "büyük ikramiye",
        "spor toto", "bahis kuponu",
        "mac orani", "mac bahsi",

        // ── Bahis siteleri (Şikayetvar top complaints) ──
        "vaycasino", "vay casino",
        "betboo", "bet boo",
        "bets10", "bets 10",
        "superbahis", "super bahis",
        "mobilbahis", "mobil bahis",
        "nakitbahis", "nakit bahis",
        "betturkey", "bet turkey",
        "tipobet", "tipo bet",
        "sultanbet", "sultan bet",
        "youwin", "tempobet", "betpas",
        "casinometropol", "casinomaxi", "retrobet",
        "bahsegel", "mariobet", "betvole", "rexbet",
        "betgram", "betlike", "hiperbet",
        "betcup", "betroad", "betorder",
        "casinotr", "casino tr",
        "bahigo", "bahi go",
        "betist", "bet ist",
        "betvakti", "bet vakti",
        "anadolucasino", "anadolu casino",
        "elexbet", "elex bet",
        "betnano", "bet nano",
        "vegabet", "vega bet",
        "goldenbahis", "golden bahis",
        "royalbet", "royal bet",
        "favoribahis", "favori bahis",
        "bettilt", "bet tilt",
        "betgaranti", "bet garanti",
        // Yeni siteler (Şikayetvar 2024-2025)
        "onwin", "on win",
        "fixbet", "fix bet",
        "sekabet", "seka bet",
        "jojobet", "jojo bet",
        "perabet", "pera bet",
        "pusulabet", "pusula bet",
        "sahabet", "saha bet",
        "matadorbet", "matador bet",
        "jetbahis", "jet bahis",
        "imajbet", "imaj bet",
        "padisahbet", "padisah bet",
        "betpark", "bet park",
        "artemisbet", "artemis bet",
        "glorybahis", "glory bahis",
        "betsat", "bet sat",
        "piabella", "piabellacasino",
        "bahisnow", "bahis now",
        "casinoplus", "casino plus",
        "diskontcasino", "discount casino",
        "casinofloor", "casino floor",
        "betexper", "bet exper",
        "betonred", "bet on red",
        "winxbet", "winx bet",
        "bettingoo",
        "kolaybet", "kolay bet",
        "bahissenin", "bahis senin",
        "megabahis", "mega bahis",
        "betoffice", "bet office",
        "casinoslot", "casino slot",
        "betasus",
        "sportsbet", "sports bet",
        "betmarino",
        "betwoon", "bet woon",
        "betkon", "bet kon",
        "casinolevant", "casino levant",
    )

    // ── LEGAL THREATS ─────────────────────────────────────────────────────────
    val LEGAL_THREAT_KEYWORDS: Set<String> = setOf(
        "icra", "icra takibi", "icra takip", "icra mudurlugu",
        "dava acilacak", "dava açılacak",
        "son uyari", "son uyarı",
        "tc kimlik", "t.c. kimlik",
        "mahkeme", "savcilik", "savcılık", "emniyet", "jandarma",
        "vergi borcu", "vergi borcunuz", "vergi cezasi", "vergi cezası",
        "sgk borcu", "sgk borcunuz", "sgk cezasi", "sgk cezası",
        "e-devlet bildirimi", "edevlet bildirimi",
        "resmi uyari", "resmi uyarı", "resmi bildirim",
        "yasal islem", "yasal işlem", "yasal surec", "yasal süreç",
        "noter tebligati", "noter tebligatı", "tebligat",
        "iflas", "iflâs", "haciz islemi", "haciz işlemi",
        "banka hesabiniz", "banka hesabınız", "hesabiniz bloke", "hesabınız bloke",
        "kartiniz iptal", "kartınız iptal",
        "kartiniz askiya", "kartınız askıya",
        "hesabiniz donduruldu", "hesabınız donduruldu",
        "odeme yapilmadi", "ödeme yapılmadı", "gecikmis odeme", "gecikmiş ödeme",
        "son odeme tarihi", "son ödeme tarihi",
        "borcunuzu odeyin", "borcunuzu ödeyin",
        // Yeni legal tehdit pattern'leri
        "cezai islem", "cezai işlem",
        "adli makam", "adli bildirim",
        "savcılığa bildirme", "savciliga bildirme",
        "suç duyurusu", "suc duyurusu",
        "hapis cezasi", "hapis cezası",
        "para cezasi", "para cezası",
        "borcunuz gecikti", "borcunuz gecikmis",
        "son ihtarname", "son ihtar",
        "ptt tebligat", "ptt bildirimi",
        "gsm hattiniz", "gsm hattınız",
        "hattiniz kapatilacak", "hattınız kapatılacak",
        "aboneliginiz iptal", "aboneliğiniz iptal",
    )

    // ── PHISHING ──────────────────────────────────────────────────────────────
    val PHISHING_KEYWORDS: Set<String> = setOf(
        "e-devlet", "edevlet",
        "hesabiniz askiya", "hesabınız askıya",
        "sifrenizi guncelleyin", "şifrenizi güncelleyin",
        "kimliginizi dogrulayin", "kimliğinizi doğrulayın",
        "hesap donduruldu",
        "acil guncelleme", "acil güncelleme",
        // Kargo phishing (Şikayetvar top)
        "kargonuz bekliyor", "kargo teslim alinamadi",
        "teslimat ucreti", "teslimat ücretiniz",
        "paket gumrukte", "paket gümrükte",
        "ptt kargo teslim",
        "kargoyu teslim alamadik",
        // Hesap phishing
        "hesabiniz kilitlendi", "hesabınız kilitlendi",
        "sifre sifirlama", "şifre sıfırlama",
        "guvenlik dogrulamasi", "güvenlik doğrulaması",
        "otp kodu giriniz",
        "dogrulama linki", "doğrulama linki",
        "hesabinizi dogrulayin", "hesabınızı doğrulayın",
        // Banka phishing
        "bankacilik sifreniz", "bankacılık şifreniz",
        "internet bankacilik", "internet bankacılık",
        "kart bilgilerinizi", "kart bilgileri guncelleme",
        "iban bilgilerinizi",
        // Sosyal medya phishing
        "instagram hesabiniz", "instagram hesabınız",
        "tiktok hesabiniz", "tiktok hesabınız",
        "hesabiniz askiya alindi", "hesabınız askıya alındı",
        "profil dogrulama", "profil doğrulama",
        "hesabiniz kaldirilacak", "hesabınız kaldırılacak",
    )

    // ── SOCIAL ENGINEERING ────────────────────────────────────────────────────
    val SOCIAL_ENGINEERING_KEYWORDS: Set<String> = setOf(
        "sosyal yardim", "sosyal yardım", "devlet yardimi", "devlet yardımı",
        "burs", "hibe",
        "ucretsiz", "ücretsiz", "bedava", "hediye",
        "tebrikler", "tebr1kler",
        "kazanan siz oldunuz", "kazanan sizsiniz", "siz kazandiniz", "siz kazandınız",
        "numaraniz secildi", "numaranız seçildi",
        "odulunuzu alin", "ödülünüzü alın", "odulunuz hazir", "ödülünüz hazır",
        "hediyeniz hazir", "hediyeniz hazır", "hediye kazandiniz", "hediye kazandınız",
        "kampanyaya katil", "kampanyaya katıl",
        "formu doldurun", "formu tamamlayin", "formu tamamlayın",
        "bilgilerinizi guncelleyin", "bilgilerinizi güncelleyin",
        "kimliginizi onaylayin", "kimliğinizi onaylayın",
        "link tiklayin", "linke tikla", "linki tikla",
        "hemen tikla", "buraya tikla",
        "whatsapptan ulasin", "whatsapp'tan ulaşın",
        "telegram grubu", "telegram kanali", "telegram kanalı",
        "kanal linki", "gruba katil", "gruba katıl",
        "qr kod okut", "qr kodu tara",
        // Çekiliş / ödül dolandırıcılığı (Şikayetvar)
        "cekilis kazandiniz", "çekiliş kazandınız",
        "otomobil kazandiniz", "otomobil kazandınız",
        "arac kazandiniz", "araç kazandınız",
        "iphone kazandiniz", "iphone kazandınız",
        "nakit odul", "nakit ödül",
        "buyuk odul", "büyük ödül",
        "para odulu", "para ödülü",
        "hediye carpi", "hediye çarpi",
        "anlık kazanim", "anlık kazanım",
        "anket doldurun", "anketi tamamlayın",
        "ucretsiz urun", "ücretsiz ürün",
        "ucretsiz abonelik", "ücretsiz abonelik",
        // WhatsApp / grup
        "gruba ekledik", "whatsapp grubuna",
        "vip gruba katil", "vip gruba katıl",
        "ozel grup linki", "özel grup linki",
    )

    // ── INVESTMENT / CRYPTO SCAMS (yeni kategori — Şikayetvar 2024-2025) ─────
    val INVESTMENT_SCAM_KEYWORDS: Set<String> = setOf(
        // Genel yatırım
        "yatirim firsati", "yatırım fırsatı",
        "yatirim danismani", "yatırım danışmanı",
        "portfoy yonetimi", "portföy yönetimi",
        "yatirim tavsiyesi", "yatırım tavsiyesi",
        "yuksek getiri", "yüksek getiri",
        "garantili getiri", "garantili kazanc", "garantili kazanç",
        "gunluk kazanc garantisi", "günlük kazanç garantisi",
        "kar garantisi",
        "pasif gelir", "pasif kazanc", "pasif kazanç",
        "10x getiri", "2x getiri", "3x getiri",
        // Borsa / forex sinyalleri
        "borsa sinyali", "forex sinyali",
        "hisse sinyali", "hisse senedi sinyali",
        "alim sinyali", "alım sinyali",
        "forex grubu", "borsa grubu",
        "vip sinyal grubu", "vip sinyaller",
        "ucretsiz sinyal", "ücretsiz sinyal",
        "forex robotu", "borsa robotu",
        "otomatik kazanc", "otomatik kazanç",
        // Kripto
        "kripto para kazan", "bitcoin kazan",
        "kripto yatirim", "kripto yatırım",
        "nft mint", "nft kazan",
        "airdrop kazan", "airdrop",
        "token dagitimi", "token dağıtımı",
        "presale", "ön satış",
        "kripto sinyal", "btc sinyali",
        "altcoin", "defi", "nft",
        // Kredi dolandırıcılığı
        "hizli kredi", "hızlı kredi",
        "aninda kredi", "anında kredi",
        "kolay kredi", "kredi onaylandi", "kredi onaylandı",
        "ihtiyac kredisi", "ihtiyaç kredisi",
        "kredi karti borcu sildirme", "kredi kartı borcu sildirme",
        "borcunuzu silelim",
        "dusuk faizli kredi", "düşük faizli kredi",
        "bankalarda reddedildiniz mi",
        "kredi notu yukseltelim", "kredi notu yükselt",
        // Emlak / ticari dolandırıcılık
        "emlak yatirim", "emlak yatırım",
        "gayrimenkul yatirim", "gayrimenkul yatırım",
        "ucuz daire", "ucuz arsa",
        "ortaklik teklifi", "ortaklık teklifi",
        "is ortakligi", "iş ortaklığı",
        "is firsati", "iş fırsatı",
        "ev kazan", "araba kazan",
    )

    // ── E-DEVLET PHİSHİNG (#14) ───────────────────────────────────────────────
    val EDEVLET_PHISHING_KEYWORDS: Set<String> = setOf(
        "e-devlet ceza", "edevlet ceza",
        "e-devlet bildirimi", "edevlet bildirimi",
        "e-devlet giris gerekli", "edevlet giris",
        "e-devlet şifre", "edevlet sifre",
        "e-devlet dogrula", "edevlet dogrula",
        "devlet kapisi giris", "devlet kapısı giriş",
        "e-devlet hesabiniz", "edevlet hesabınız",
        "e-devlet uyarisi", "edevlet uyarısı",
        "e-devlet borcunuz", "edevlet borcunuz",
        "e-devlet tebligat", "edevlet tebligat",
        "tc kimlik dogrulama", "tc kimlik doğrulama",
        "kimlik bilgilerinizi guncelleyin",
        "nufus mudurlugu bildirimi",
        "devlet destegi basvurusu", "devlet desteği başvurusu",
        "sosyal yardim basvurusu onaylandi",
    )

    val EDEVLET_DOMAIN_PATTERNS: List<Regex> = listOf(
        Regex("""e-?devlet[-.]?(tr|gov|giris|login|portal|net|com|site|online)\.""", RegexOption.IGNORE_CASE),
        Regex("""edevlet\d+\.""", RegexOption.IGNORE_CASE),
        Regex("""devlet-?(kapisi|portal|giris)\.""", RegexOption.IGNORE_CASE),
        Regex("""turkiye-?(devlet|hukumet)\.""", RegexOption.IGNORE_CASE),
    )

    // ── KARGO DOLANDIRICILIK (#16) ────────────────────────────────────────────
    val CARGO_SCAM_KEYWORDS: Set<String> = setOf(
        // Teslimat ücret tuzağı
        "kargonuz teslim edilemedi", "kargo teslim edilemedi",
        "teslimat ucreti odemesi", "teslimat ücreti ödemesi",
        "kargo ucret odeme", "kargo ücret ödeme",
        "kargo gumruk ucreti", "kargo gümrük ücreti",
        "gumruk vergisi odeme", "gümrük vergisi ödeme",
        "paketiniz gumrukte", "paketiniz gümrükte",
        "kargo adresi guncelleme", "kargo adresi güncelleme",
        "teslimat adresi dogrulama", "teslimat adresi doğrulama",
        "kargo takip linki",
        // Sahte kargo bildirimleri
        "ptt kargo ucreti", "ptt kargo ücretiniz",
        "aras kargo bildirim", "aras kargo teslimat",
        "mng kargo ucret", "mng kargo ücret",
        "yurtici kargo guncelle", "yurtiçi kargo güncelle",
        "surat kargo teslim", "sürat kargo teslim",
        "ups kargo gumruk", "dhl kargo gümrük",
        // Paket bekliyor tuzağı
        "paketiniz depodan iade", "paketiniz iade edilecek",
        "kargo iade edilmeden once", "kargo iade edilmeden önce",
        "teslimat pencerenizi secin", "teslimat pencerenizi seçin",
        "kargo ucretini yatirin", "kargo ücretini yatırın",
    )

    // ── BANKA SMS DOĞRULAMA (#15) ─────────────────────────────────────────────
    val BANK_PHISHING_KEYWORDS: Set<String> = setOf(
        // Sahte banka temsilcisi
        "banka musteri temsilcisi", "banka müşteri temsilcisi",
        "banka guvenlik birimi", "banka güvenlik birimi",
        "bankacilik guvenlik uyarisi", "bankacılık güvenlik uyarısı",
        "bankacilik sisteminiz kilitlendi",
        // Sahte kart/hesap güncelleme
        "kart bilgilerinizi dogrulayin", "kart bilgilerinizi doğrulayın",
        "kart limiti guncelleme", "kart limiti güncelleme",
        "iban numaranizi dogrulayin",
        "hesap dogrulama islemi", "hesap doğrulama işlemi",
        "internet bankacilik sifreniz", "internet bankacılık şifreniz",
        "mobil bankacilik guncelleme", "mobil bankacılık güncelleme",
        // Sahte para transferi
        "hesabinizdan para transferi", "hesabınızdan para transferi",
        "izinsiz para cekimi", "izinsiz para çekimi",
        "anlik para transferi onaylayin", "anlık para transferi onaylayın",
        "havale isleminizi onaylayin", "havale işleminizi onaylayın",
        // OTP/SMS kodu tuzağı
        "banka dogrulama kodu", "banka doğrulama kodu",
        "sms kodunuzu paylasin", "sms kodunuzu paylaşın",
        "tek kullanim kodunuz", "tek kullanım kodunuz",
        "otp kodunuzu giriniz",
        "guvenlik kodunuzu bildirin", "güvenlik kodunuzu bildirin",
        // Masraf iadesi tuzağı
        "masraf iadesi basvurusu", "masraf iadesi başvurusu",
        "komisyon iadesi icin", "komisyon iadesi için",
        "geri odeme linki", "geri ödeme linki",
    )

    // ── URL PATTERNS ─────────────────────────────────────────────────────────
    val SHORT_URL_PATTERNS: List<Regex> = listOf(
        Regex("""bit\.ly/\S+"""),
        Regex("""tinyurl\.com/\S+"""),
        Regex("""t\.co/\S+"""),
        Regex("""ow\.ly/\S+"""),
        Regex("""rebrand\.ly/\S+"""),
        Regex("""tr\.im/\S+"""),
        Regex("""kisa\.link/\S+"""),
        Regex("""cutt\.ly/\S+"""),
        Regex("""is\.gd/\S+"""),
        Regex("""v\.gd/\S+"""),
        Regex("""x\.co/\S+"""),
        Regex("""u\.to/\S+"""),
        Regex("""7\.ly/\S+"""),
        Regex("""link\.tl/\S+"""),
        Regex("""shorturl\.at/\S+"""),
        Regex("""rb\.gy/\S+"""),
        Regex("""tiny\.cc/\S+"""),
    )

    // ── SUSPICIOUS DOMAINS ────────────────────────────────────────────────────
    val SUSPICIOUS_DOMAIN_PATTERNS: List<Regex> = listOf(
        Regex("""e-?devlet[a-z0-9\-]*\.(com|net|org|xyz|info|co|site|online)""", RegexOption.IGNORE_CASE),
        Regex("""garanti[a-z0-9\-]+\.(com|net|org|xyz|site|online)""", RegexOption.IGNORE_CASE),
        Regex("""isbank[a-z0-9\-]+\.(com|net|org|xyz|site|online)""", RegexOption.IGNORE_CASE),
        Regex("""akbank[a-z0-9\-]+\.(com|net|org|xyz|site|online)""", RegexOption.IGNORE_CASE),
        Regex("""ziraat[a-z0-9\-]+\.(com|net|org|xyz|site|online)""", RegexOption.IGNORE_CASE),
        Regex("""vakifbank[a-z0-9\-]+\.(net|org|xyz|co|site|online)""", RegexOption.IGNORE_CASE),
        Regex("""enpara[a-z0-9\-]+\.(com|net|org|xyz|site|online)""", RegexOption.IGNORE_CASE),
        Regex("""yapikredi[a-z0-9\-]+\.(com|net|org|xyz|site)""", RegexOption.IGNORE_CASE),
        Regex("""ykb[a-z0-9\-]+\.(com|net|org|xyz)""", RegexOption.IGNORE_CASE),
        Regex("""qnb[a-z0-9\-]+\.(com|net|org|xyz)""", RegexOption.IGNORE_CASE),
        Regex("""halkbank[a-z0-9\-]+\.(com|net|org|xyz)""", RegexOption.IGNORE_CASE),
        Regex("""denizbank[a-z0-9\-]+\.(com|net|org|xyz)""", RegexOption.IGNORE_CASE),
        Regex("""ptt[a-z0-9\-]+\.(com|net|org|xyz|site)""", RegexOption.IGNORE_CASE),
        Regex("""sgk[a-z0-9\-]+\.(com|net|org|xyz|site)""", RegexOption.IGNORE_CASE),
    )

    // ── TRUSTED SENDERS ───────────────────────────────────────────────────────
    val TRUSTED_SENDER_IDS: Set<String> = setOf(
        // Bankalar
        "Akbank", "AkbankSMS", "AKBANK",
        "Garanti", "GarantiBBVA", "GARANTIBBVA",
        "Isbank", "ISBANK",
        "Yapikredi", "YAPIKREDI",
        "Ziraat", "ZiraatBankasi", "ZIRAAT",
        "Halkbank", "HALKBANK",
        "Vakifbank", "VAKIFBANK",
        "DenizBank", "Denizbank", "DENIZBANK",
        "QNBFinansbank", "Finansbank", "FINANSBANK",
        "HSBC", "HSBCBank",
        "ING", "INGBank",
        "Odeabank", "ODEABANK",
        "TEB", "CEPTETEB",
        "Sekerbank", "SEKERBANK",
        "Fibabanka", "FIBABANKA",
        "Enpara",
        // Operatörler
        "Turkcell", "TURKCELL",
        "Vodafone", "VODAFONE",
        "TurkTelekom", "TURKTELEKOM",
        "Bimcell", "BIMCELL",
        // E-ticaret / kargo
        "Trendyol", "TRENDYOL",
        "Hepsiburada", "HEPSIBURADA",
        "Amazon", "AmazonTR",
        "n11", "N11",
        "GittiGidiyor", "GITTIGIDIYOR",
        "Morhipo", "MORHIPO",
        "Ciceksepeti", "CICEKSEPETI",
        "PTT", "PTTAVM", "PTTKargo",
        "YurticiKargo", "YURTICI",
        "ArasKargo", "ARASKARGO",
        "MNGKargo",
        "SuratKargo",
        "Sendeo", "SENDEO",
        "Borusan", "BORUSAN",
        "DHL", "UPS", "FedEx",
        // Devlet / kamu
        "eDevlet", "EDEVLET",
        "SGK", "BTK", "BDDK",
        "GIB", "TEDAS", "AYEDAS",
        "IGDAS", "GAZDAS", "ISKI",
        "Belediye",
        "Nufus",
        // Yaygın servisler
        "Netflix", "Spotify", "YouTube",
        "Google", "Apple", "Microsoft",
        "PayPal", "PayTR", "Iyzico",
        "BiTaksi", "Uber", "Bolt",
        "Yemeksepeti", "Getir", "Migros",
        "A101", "BIM", "SOK",
        "Lcwaikiki", "LCWAIKIKI",
        "Mediamarkt", "MEDIAMARKT",
        "Teknosa", "TEKNOSA",
        "Boyner", "BOYNER",
        "Koton", "KOTON",
        "DeFacto", "DEFACTO",
        "Mavi", "MAVI",
    )
}
